name: Generate Proto Go Files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ← ДОБАВЬТЕ ЭТО

    steps:
      - name: Checkout Generator Repository
        uses: actions/checkout@v4

      - name: Install Protocol Buffers Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/bekasyl00/my-protos.git

      - name: Generate Go Code from Proto Files
        run: |
          mkdir -p proto
          find my-protos/proto -name "*.proto" | while read file; do
            protoc \
              --proto_path=my-protos \
              --go_out=. \
              --go-grpc_out=. \
              "$file"
          done

      - name: Commit and Push Generated Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "auto-generate pb.go files" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/bekasyl00/my-protos-gen.git HEAD:main